ALTER TABLE users
    ADD COLUMN email VARCHAR(45) NOT NULL;

ALTER TABLE users
ALTER COLUMN password TYPE VARCHAR(255);

ALTER TABLE users
    ALTER COLUMN password SET NOT NULL;

ALTER TABLE users
ALTER COLUMN role TYPE SMALLINT USING role::smallint;