name: Deploy to Production
on:
  push:
    branches: [deploy-github-actions]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: actions
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login DockeHub
        uses: docker/login-action@v2
#        utilizar token gerado no dockerhub ao invés da senha
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Image
        run: docker build -t caiomotoboy/deploy_ghactions .
      - name: Push Image Docker
        run: docker push caiomotoboy/deploy_ghactions

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: sudo docker pull caiomotoboy/deploy_ghactions
      - name: Remove old container
        run: sudo docker rm -f deploy_ghactions
      - name: Run docker container
        run: sudo docker run -d --name deploy_ghactions -p 8080:8080 -e DATABASE_USER=${{secrets.DATABASE_USER}} -e DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} -e DATABASE_URL=${{secrets.DATABASE_URL}} caiomotoboy/deploy_ghactions