name: Deploy to Production
on:
  push:
    branches: [deploy-github-actions]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build project
        run: mvn clean install -DskipTests
      - name: Login DockeHub
        run: echo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} --password-stdin
      - name: Docker Image
        run: docker build -t caiomotoboy/deploy_ghactions-1.0.0.jar .
      - name: Push Image Docker
        run: docker push caiomotoboy/deploy_ghactions-1.0.0.jar